// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy, Suspense } from "react";
import { RouteObject } from "react-router";
import { UserGuard } from "app";

const ActivityDetails = lazy(() => import("./pages/ActivityDetails.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ChatDetail = lazy(() => import("./pages/ChatDetail.tsx"));
const Chats = lazy(() => import("./pages/Chats.tsx"));
const Create = lazy(() => import("./pages/Create.tsx"));
const Feed = lazy(() => import("./pages/Feed.tsx"));
const Friends = lazy(() => import("./pages/Friends.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const OtherUserProfile = lazy(() => import("./pages/OtherUserProfile.tsx"));

// Utility function to wrap components in Suspense
const withSuspense = (element: React.ReactNode) => (
  <Suspense fallback={<div>Loading...</div>}>{element}</Suspense>
);

export const userRoutes: RouteObject[] = [
  { path: "/activity-details", element: withSuspense(<UserGuard><ActivityDetails /></UserGuard>) },
  { path: "/activitydetails", element: withSuspense(<UserGuard><ActivityDetails /></UserGuard>) },
  { path: "/", element: withSuspense(<App />) },
  { path: "/chat-detail", element: withSuspense(<UserGuard><ChatDetail /></UserGuard>) },
  { path: "/chatdetail", element: withSuspense(<UserGuard><ChatDetail /></UserGuard>) },
  { path: "/chats", element: withSuspense(<UserGuard><Chats /></UserGuard>) },
  { path: "/create", element: withSuspense(<UserGuard><Create /></UserGuard>) },
  { path: "/feed", element: withSuspense(<UserGuard><Feed /></UserGuard>) },
  { path: "/friends", element: withSuspense(<UserGuard><Friends /></UserGuard>) },
  { path: "/login", element: withSuspense(<Login />) },
  { path: "/logout", element: withSuspense(<UserGuard><Logout /></UserGuard>) },
  { path: "/profile", element: withSuspense(<UserGuard><Profile /></UserGuard>) },
  { path: "/otherprofile", element: withSuspense(<UserGuard><OtherUserProfile /></UserGuard>) },
];
